### ISSUE TITLE
Variables like `temp` should contain an indicator of the unit in the name.

### ISSUE THREAD

**Issue by andreas-bauer** [PerssonAlbin/weatherterminal#1]
Variables that contain a value that is only interpretable in relation to its unit should have a name that reflects the unit of the value.
Thus, instead of using `temp` as a variable name, add the unit: `temp_kelvin` or `temp_celsius`.
Otherwise, it will become hard and error-prone to handle `temp`, not knowing which unit it represents in a specific part of the program.

```c
// bad
double temp = weatherInfo["temp"].template get<double>();

// better

double temp_kelvin = weatherInfo["temp"].template get<double>();

temp_celsius = convertToCelsius(temp_kelvin);
std::cout << int(temp_celsius) << "°" << std::endl;
```

**Comment by PerssonAlbin** [comment]
Thanks, fixed in the latest commit!
