### ISSUE TITLE
Handling differnt temperature units

### ISSUE THREAD

**Issue by andreas-bauer** [PerssonAlbin/weatherterminal#2]
To handle the different temperature units, I propose the following:

1) An API request should always return the temperature in Kelvin.
2) Internally, the app used the Kelvin representation.
3) Config store the user preference to represent the data (but not to request data).

```c
double temp_kelvin = weatherInfo["temp"].template get<double>();

someProcessing(temp_kelvin);

if (config.temp_unit == CELSIUS) {
   std::cout << int(toCelsius(temp_kelvin)) << "° C" << std::endl;
} else if (config.temp_unit == FAHRENHEIT) {
   std::cout << int((toFahrenheit(temp_kelvin)) << "° F" << std::endl;
}


```

**Comment by PerssonAlbin** [comment]
Yes, this is how it works currently! However didn't think about Fahrenheit as possibility as well. 

Working on a Readme so it will get more clear hopefully!

**Comment by PerssonAlbin** [comment]
It's been implemented now so the temp unit can be celsius, kelvin and fahrenheit. You can also checkout the readme for more info!
